### ISSUE TITLE
i recommend the usage of zod instead of typebox

### ISSUE THREAD

**Issue by Victugord** [elysiajs/elysia#11]
with Zod you can have the static type inference and a validator at the same time (https://zod.dev/)

**Comment by izakfilmalter** [comment]
@Victugord You can get the type similarly to Zod. I would prefer Zod since my whole code base uses it but, this works.
```ts
import { Static } from '@sinclair/typebox'
import { t } from 'elysia'

const Test = t.Undefined()
type Test = Static<typeof Test>
```

**Comment by SaltyAom** [comment]
I have been experimenting with TypeBox and Zod back then in the beta day in fact I did ship Zod in some versions before migrating to TypeBox, because I have some problems back then that I don't remember anymore, mainly a performance difference between Zod and TypeBox (see [benchmark](https://moltar.github.io/typescript-runtime-type-benchmarks)).

As performance is a critical factor for the server side, and find that TypeBox is a good trade-off for that, I decided that Elysia will be using TypeBox as a primary method, and might support Zod later as I've been focusing on some other areas at the moment.

TypeBox does the validation and also has Static Type Inference which made [Eden](https://elysiajs.com/collections/eden.html) happens by using Static Type Inference.

You can get type inference using the following code:
```typescript
import { Elysia, t, type UnwrapSchema } from 'elysia'

const UserSchema = t.Object({
	user: t.String()
})

type UserSchema = UnwrapSchema<typeof UserSchema>
```

Fun fact: I also prefer Zod over TypeBox on the client side.

**Comment by SaltyAom** [comment]
Close as we have no plan to migrate to Zod in the near future.

Will re-open once we planned to migrate.

**Comment by MuhammadAli-208** [comment]
any future plan to consider `Zod` as a type provider?

**Comment by felipedeboni** [comment]
I also would like to use another validator, was doing a quick evaluation on Elysia and returning custom error messages when validation fails is extremely cumbersome.

While I understand performance matters, delivering the proper error messages to our users, does too.

Issues faced:

* TypeBox lacks of `flatten` method available on both `zod` and `valibot`. After digging around, I've found https://github.com/sinclairzx81/typebox/issues/1044
 
* Ability to set a message for each validation rule of a property easily (or at all).

```tsx
v.pipe(
  v.string('A message.'),
  v.email('A different message.'),
  v.custom((input) => input.includes('@someplace.com'), 'You got the idea.')
)
```

on error handler:

```tsx
return {
  errors: flatten(error.details.issues).nested // basically it returns a Record<string, string[]>
}
```

Tried `@sinclair/typemap`, but it just ignores the messages and custom does not work at all, understandable to TS type, but the validation does not even is applied.

Using the `error` function is really verbose and I gave up when it didn't work:

```tsx
import { ValueErrorType } from "@sinclair/typebox/errors";

t.Object({
  "email": t.String({
    minLength: 1,
    format: "email",
    error({ type, validator, errors, value }) {
      switch (type) {
        case ValueErrorType.StringMinLength: // Type ... is not comparable to type string
          return 'A message';
      }
      return '...';
    },
  }),
}),
```
Ref: https://github.com/sinclairzx81/typebox?tab=readme-ov-file#error-function

Valibot is faster than Zod but slower than TypeBox, however DX and ease of use is years ahead, btw both Zod and Valibot supports Standard Schema nowadays.

Please let me know if I am doing something wrong of course :)

**Comment by Eptagone** [comment]
I also prefer to use `zod` over `typebox`
