### ISSUE TITLE
Hot Reload issue

### ISSUE THREAD

**Issue by namcogit** [elysiajs/elysia#125]
Been trying to use the Hot Reload feature for front end did `--watch` and `--hot` but saving the file doesn't reload the page in the browser, funny thing is that creating a solo bun app with hot reload also doesn't work.

**index.ts**
```
import { Elysia } from "elysia";

const app = new Elysia().get("/", () => "Hello Elysia check yoy yoyoy").listen(3001);

console.log(
  `🦊 Elysia is running at ${app.server?.hostname}:${app.server?.port}`
);
```

**Package.json**
```
{
  "name": "TestApp",
  "version": "1.0.50",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "dev": "bun run --watch src/index.ts"
  },
  "dependencies": {
    "elysia": "latest"
  },
  "devDependencies": {
    "bun-types": "latest"
  },
  "module": "src/index.js"
}
```

Tried both `bun --watch run ./src/index.ts` and `bun --hot run ./src/index.ts` I guess `--hot` would've worked?

**Comment by ethanniser** [comment]
bun watch flag only restarts the actual running process
so the elysia server gets restarted on every change

the browser updating is completely separate, it has no clue that the backend server has restarted and so is still just showing the result of the last http call

**Comment by fruity4pie** [comment]
`--hot `works fine - it restarts the server on every change

**Comment by namcogit** [comment]
> bun watch flag only restarts the actual running process so the elysia server gets restarted on every change
> 
> the browser updating is completely separate, it has no clue that the backend server has restarted and so is still just showing the result of the last http call

https://github.com/elysiajs/elysia/issues/4#issuecomment-1366748546

so how do I reload page automatically when code has been changed?

**Comment by GGAlanSmithee** [comment]
> saving the file doesn't reload the page in the browser

I don't think there is built in live reload in bun and/or Elysia.

There seems to be a couple of different ways to do it, but I have found that each method comes with it's own set of problems. Having full - with SPA state being kept intact across live reloads - is a hard problem.

After trying out a lot of different approaches, I found a super simple solution for my own stack - see code below.

Note, however, that this is not for a SPA. so the "live reload" simply swaps the entire content of the current page. ie. does not keep state (since there is no browser state, it's all on the server).


```tsx
// server.ts

// globalThis is not replaced on HMR
declare global {
  var ws: ElysiaWS<any>
  var isOpened: boolean
}

const app = new Elysia()

app.use(html())
app.use(ws())

app.ws(`/live-reload`, {
  open: (ws) => {
    globalThis.ws = ws
  }
})

// routes etc

// open browser if first execution, othervise reload out active browser tab
const callback: ListenCallback = async ({ hostname, port, }) => {
  if (!globalThis.isOpened) {
    globalThis.isOpened = true
    open(`http://${hostname}:${port}`) // https://www.npmjs.com/package/open
  }

  if (globalThis.ws) globalThis.ws.send('live-reload')
}

app.listen(5000, callback)
```

```html
<!-- somewhere in your html -->
<script type="text/javascript">
  (function() {
    const socket = new WebSocket("ws://localhost:5000/live-reload");
      socket.onmessage = function(msg) {
      if(msg.data === 'live-reload') {
        location.reload()
      }
    };
    console.log('Live reload enabled.');
  })();
</script>
```

The only issue I have encountered is that added files does not always trigger a HMR, but I have worked around that for now, by simply saving an existing file after adding a new. This might be due to some dynamic imports I have though.

Also, see this https://github.com/aabccd021/bun-html-live-reload/tree/main for a more general approach

**Comment by marcospgp** [comment]
arriving from google, there is HMR and hot reloading in bun, is it supported in elysia currently?

**Comment by qimingweng** [comment]
I am curious about this too. Bun 1.3’s full stack react features include HMR now.

Elysia’s docs mention supporting HMR but it’s not clear where that’s set up.
