### ISSUE TITLE
Support for Alpine.js

### ISSUE THREAD

**Issue by Wotan6891** [elysiajs/elysia#14]
Hello,

I have been looking at the framework, and I congratulate you.

I don't know much about programming. I am recently learning. I use Laravel and have been learning alpine.js

So my question is:

Can I use alpine.js without having to use pure JavaScript or typescript?

**Comment by hisamafahri** [comment]
Hi @Wotan6891, you can use elysia as your "backend" framework since it will expose a REST endpoint that you can use with a lot of frontend framework/clients. You can refer to [this blog](https://postsrc.com/code-snippets/how-to-feetch-api-in-alpine-js) for example on how to do that.

> Can I use alpine.js without having to use pure JavaScript or typescript?
I think you can raise an issue/questions directly to the [alpine.js](https://github.com/alpinejs/alpine) community for this one.

Keep learning

**Comment by SaltyAom** [comment]
As @hisamafahri, you can use Elysia with any frontend framework, while you might see other requests for Remix support for example is requested for Server Side Rendering. 

As I'm afraid that, there's no SSR support for Alpine yet to my knowledge, so you can fully use Elysia with Alpine.js 100% without needing an extra plugin from Elysia.

Elysia acts as the backend REST API server for your Alpine frontend with normal [fetch](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API) or [Eden](https://elysiajs.com/collections/eden), and use something like PHP_curl for Laravel server to fetch data from Elysia.
