### ISSUE TITLE
Cannot get content-disposition from multipart/form-data

### ISSUE THREAD

**Issue by iamcsharper** [elysiajs/elysia#154]
The form parsing mechanism in elysia simply skips the meta data in the body.

As we know, the typical structure for body in multipart/form-data schema is:

```
POST /upload
Host: example.com
Content-Length: 2740
Content-Type: multipart/form-data; boundary=abcde12345

--abcde12345
Content-Disposition: form-data; name="orderId"

1195
--abcde12345
Content-Disposition: form-data; name="userId"

545
--abcde12345
Content-Disposition: form-data; name="fileName"; filename="attachment.txt"
Content-Type: text/plain

[file content goes there]
--abcde12345--
```

Content-Disposition is just skipped, when I would like to have it parsed and stored somewhere (headers?)

I tried to manually process request.body, but due to streaming mechanisms, its already read by elysia internal code, so I can't

Please let me know if its a problem of bun, not elysia

**Comment by bogeychan** [comment]
Hi 👋

ElysiaJS uses https://github.com/elysiajs/elysia/blob/741ffe7659cf049c8627d30b91cd1f05cfbab53e/src/dynamic-handle.ts#L101 under the hood. So it's a problem with Bun because the API doesn't provide a way to read additional headers like `Content-Disposition`:

https://github.com/oven-sh/bun/blob/75697890ce1040d2c2f9bc50499faf54b3205915/packages/bun-types/globals.d.ts#L838

If you wanna parse the body of the request yourself you can do it like this:

```ts
const app = new Elysia()
  .onRequest(async (ctx) => {
    const formData = await ctx.request.formData();
    return formData.get('file');
  })
  .post(
    '/upload',
    async ({ body }) => {
      return body; // body = formData.get('file')
    },
    {
      body: t.File()
    }
  )
```

**Comment by Coachonko** [comment]
Has there been any change? I have been blocked by this issue today.
