### ISSUE TITLE
make the 'bun create elysia app' a button that copies the command to clipboard

### ISSUE THREAD

**Issue by OmerDavidson** [elysiajs/elysia#163]
when opening the documentation, I am greeted with this beautiful home page.
![image](https://github.com/elysiajs/elysia/assets/59133159/74b3e4e1-a922-4149-8c6b-4f67893c9414)
the first thing I tried to do was click the  'bun create elysia app'  button. only it is not a button and has no functionality.

making it a button that copies the command to the clipboard will let newcomers get started slightly quicker.

I would also like to add a little toast popup to let the user know I copied something to their clipboard

**Comment by kravetsone** [comment]
@SaltyAom Can close this issue because the documentation has been rewritten) and this feature is now implemented on the site
![image](https://github.com/elysiajs/elysia/assets/57632712/e66021ab-4890-4fe7-8595-5cd02dabfc96)

![image](https://github.com/elysiajs/elysia/assets/57632712/87501073-9da7-4428-91e6-f54d260efa3d)
