### ISSUE TITLE
[Feature Request] Server Sent Events (SSE) Plugin 

### ISSUE THREAD

**Issue by go4cas** [elysiajs/elysia#24]
The Elysia ecosystem includes a great collection of plugins (including websockets). It would be great if the team could add an official SSE plugin.

**Comment by JulianCataldo** [comment]
Giving a try:

```ts
  .get("/sse", ({ set }) => {
    const stream = new ReadableStream({
      start(controller) {
        setInterval(() => {
          controller.enqueue(`data: hey\n\n`);
        }, 1000);
      },
      cancel() {},
    });

/*
Argument of type 'ReadableStream<any>' is not assignable to parameter of type 'BlobPart | BlobPart[]'.
  Type 'ReadableStream<any>' is missing the following properties from type 'BlobPart[]': length, pop, push, concat, and 29 more.ts(2345)
const stream: ReadableStream<any>
*/

    return new Response(stream, {
      headers: {
        "Content-Type": "text/event-stream",
        Connection: "keep-alive",
        "Cache-Control": "no-cache",
      },
    });
  })
```

```html
    <script>
      const source = new EventSource("/sse");

      console.log({ source });

      source.addEventListener("message", (e) => {
        console.log(e);
      });
    </script>
```


Not really working, but it's a start.
Events come not one by one every 1 sec like it should,
but by chunks of ~20-ish, probably because of the timeout.

Cheers

**Comment by SaltyAom** [comment]
Blocking on: https://github.com/oven-sh/bun/issues/2443

**Comment by cirospaciari** [comment]
You can use HTTP / 1.1 at this moment until we add support for HTTP / 2

Flush was fixed by https://github.com/oven-sh/bun/pull/3073

This should work on the next version:
```ts
function sendSSECustom(controller: ReadableStreamDirectController, eventName: string, data: string) {
  return controller.write(`event: ${eventName}\ndata:${JSON.stringify(data)}\n\n`);
}
function sendSSEMessage(controller: ReadableStreamDirectController, data: string) {
  return controller.write(`data:${JSON.stringify(data)}\n\n`);
}
function sse(req: Request): Response {
  const signal = req.signal;
  return new Response(
    new ReadableStream({
      type: "direct",
      async pull(controller: ReadableStreamDirectController) {
        while (!signal.aborted) {
          await sendSSECustom(controller, "bun", "Hello, World!");
          await sendSSEMessage(controller, "Hello, World!");
          await controller.flush();
          await Bun.sleep(1000);
        }
        controller.close();
      },
    }),
    { status: 200, headers: { "Content-Type": "text/event-stream" } },
  );
}
Bun.serve({
  port: 3000,
  fetch(req) {
    if (new URL(req.url).pathname === "/stream") {
      return sse(req);
    }
    return new Response("Hello, World!");
  },
});
```
You may will wanna use something like lastEventId to resume reconnections (by sending `id:`), and send `retry:` to control retry intervals.
```js
const lastEventId = req.headers.get("last-event-id")
```
For consuming on the server side we will add support to the client soon.

**Comment by paperdave** [comment]
bun will have a builtin helper for doing SSE: `Bun.EventStream` (https://github.com/oven-sh/bun/pull/3390). It would be cool to see Elysia and other frameworks integrate this, and it should be pretty straightforward too.

today you can use [`new ReadableStream({ type: "direct", pull })`](https://bun.sh/docs/api/streams#direct-readablestream) which is a bun-specific feature that passes a direct writer to `pull`, making it extremely low overhead. `cancel` on this is broken at the moment but will be fixed in the pr.

the regular readable streams don't work just yet but i'm looking into how much work it would be to make it happen.

**Comment by go4cas** [comment]
@SaltyAom ... there seems to be movement on this. You think you'll be able to add an SSE plugin for Elysia?

**Comment by SaltyAom** [comment]
Closing with the introduction of [Stream plugin](https://elysiajs.com/plugins/stream.html#stream-plugin)

demo: https://x.com/saltyAom/status/1716759147109330972?s=20
