### ISSUE TITLE
route path parsing not matching express/fastify

### ISSUE THREAD

**Issue by Sewdn** [elysiajs/elysia#296]
Hi,

It looks like the path parsing is not working like express or fastify (although the documentation points to them as reference: https://elysiajs.com/concept/route.html)

For example, when using this pathMatch `/:id/:filename.:ext`, the path `/test/foo.png` does not match (because `ext` is not optional) and the match results in:
```
{
  id: 'test',
  filename: 'foo.png'
}
```
while I would expect:
```
{
  id: 'test',
  filename: 'foo',
  ext: 'png'
}
```

Testing this path matching using express-route-tester works as expected (in all versions):
https://forbeslindesay.github.io/express-route-tester/

I now have to use a workaround to split the extension in the handler.

Hope this helps!
Btw: keep up the good work. I love ElysiaJS and it quickly became my goto node (Bun!) framework of choice!

**Comment by SaltyAom** [comment]
We don't support path matching like this using string literal.

However, we do support this approach by using [decoder](https://elysiajs.com/blog/elysia-07.html#typebox-0-31), or using [transform](https://elysiajs.com/concept/life-cycle.html).

We are not going to support path matching using string literal due to:
1. Performance reason.
2. You can have full control over the path matching using a decoder rather than limiting it to what Elysia provided.

Feels free to reopen the discussion if this doesn't answer your question.
