### ISSUE TITLE
Proposal: Rename and split some methods to better represent their intended usage

### ISSUE THREAD

**Issue by izznatsir** [elysiajs/elysia#34]
While trying to implement a logging library inspired by [tracing crate](https://docs.rs/tracing/latest/tracing/) from Rust ecosystem, I stumbled upon the `decorate`, `state`, and `derive` methods. It's not immediately clear the call-time and the usage of the `state` and `derive` methods from their names. Below is my proposal to potentially improve the naming of those methods:

- `state` -> `setStore`
By renaming it to `setStore`, it's immediately clear that the value is stored in `store` property.
- `derive` -> split into `deecorateOnRequest` and `setStoreOnRequest`
`derive` is not accurate because user does not always have to derive from the existing context, it also useful to set decoration or state that is unique for each request. For example, one of the main feature of the `tracing` crate is to set a request-bound identifier to correlate logs that being emitted non-sequencially (asynchronous). `derive` can be used for that purpose, set a decoration closure function called log that bound to a unique identifier. The split is to maintain consistency with `setStore` and `decorate` methods while also establish correlated meanings that `setStore` and `decorate` is assigned once on the server startup instead of called before each request.

**Comment by SaltyAom** [comment]
Hi, sorry for the slow response, I have just back from vacation in Japan and didn't read the mail while I was there.

I agree with the `state` -> `setStore` to match the naming convention with `setModel`.

However, I disagree with `derive` -> `decorateOnRequest` and `setStoreOnRequest`, although it's clear what it does, mainly because the naming is a little bit too long. 

The main reason I name `derive` as `derive` is because it's short and easy to type and read, and the word `derive` means that it will be based on a predefined value, so itself will not be predefined.

I agree with the `setStoreOnRequest` as we are missing the functionality provided below, however as same as the previous point, the naming was a bit too long.

| type      | Predefined | Define on Request |
| --------| ----------- | ------------------ |
| store     | state           | ?                              |
| context | decorate    | derive                     |

I will ask some opinion about the naming of `derive` and `setStoreOnRequest`.

**Comment by izznatsir** [comment]
The long names might not be a big deal for most people, with IDEs provided autocomplete feature. My assumptions mught be wrong though.

**Comment by TranquilMarmot** [comment]
I am still a bit confused about the difference between `store` and `context` here. It's not clear to me when to use `state` (static values?) and when to use `decorate` (???).

From the table above, it's at least a little more obvious that `derive` is _per-request_ whereas `state` and `decorate` are for the current instance. It would be great if that was explained a little better in the docs.
