### ISSUE TITLE
If error is instanceof Response, respond with it

### ISSUE THREAD

**Issue by dodas** [elysiajs/elysia#385]
It would be handy to be able to throw a `Response` and have elysia respond with it.
For example, if an error occurs in `derive` we can throw the error-y response, instead of returning the context (which we were not able to compute due to error).

This can be currently fixed by doing this:
```
new Elysia()
  .onError(({ error }) => {
    if (error instanceof Response) {
      return error;
    }
  })
```

could we have this built-in?

**Comment by SaltyAom** [comment]
Thanks for the idea, now implement in 0.8.7

**Comment by dodas** [comment]
Thanks!

**Comment by gitblit** [comment]
@SaltyAom my Eden tests caught the difference in endpoint response due to this change.

Two questions on this:
- the response now includes a stacktrace... are those always included even in a production responses?
- is Elysia following semantic versioning during the pre-1.0 development phase? it's fine if it does not, I was just surprised by the change in contract on a build/patch release.
