### ISSUE TITLE
Insanely slow type inference?

### ISSUE THREAD

**Issue by verydanny** [elysiajs/elysia#394]
After building out basic login, only a few pages, it takes a solid 2-3 seconds for types to appear. I'm trying to figure out if this is my setup. 

[Pull Request](https://github.com/verydanny/elysia-backend/pull/2)

I'm running:
```
Bun 1.0.21
macOS 14.2.1
```

```
M2 Max 32GB
```

**Comment by itsanji** [comment]
I'm having the same issue.
any update?

My PC:
```
OS: phyOS x86_64 ( Arch Linux ) 
CPU: Intel i7-2600K (8) @ 3.800GHz
GPU: NVIDIA Geforce RTX 3050
Memory: 11931MiB
```

**Comment by SaltyAom** [comment]
The issue was reported around 0.8.x.

The subsequent version has been updated with up to 13x faster type inference in 1.0 as mentioned in [Type Inference improvement](https://elysiajs.com/blog/elysia-10.html#type-inference-improvement)
<img width="772" alt="Screenshot 2567-08-31 at 01 14 42" src="https://github.com/user-attachments/assets/e5b20246-aaaf-434d-aeb5-e10e179a5a67">

If the type is still not fast enough (longer than 0.5s-1s), feels free to create a new issue. Thanks.
