### ISSUE TITLE
Remove default export in favor of the named one

### ISSUE THREAD

**Issue by dodas** [elysiajs/elysia#396]
Currently Elysia exports both named export `Elysia` and a `default` exports as well, which equals to the named one.
This can lead to inconsistent imports in codebases – we are already seeing occurrences of both in our codebase.
I propose removing the default export in favor of the named `Elysia` export to avoid inconsistency/confusion.

**Comment by BLucky-gh** [comment]
I second this. On top of the obvious "two ways to do the same thing is confusing and error prone" and "default exports are a minefield", I wasted a full day recently due to an issue with esm/cjs interop in bundlers for node: since Elysia explicitly exports the cjs version as the node version, bundlers are forced into using the cjs version even if the target is esm, and esm/cjs interop has the problem of cjs `default` exports going under `default.default` in esm

**Comment by SaltyAom** [comment]
Elysia now exports esm and cjs separately as follows:
```json
{
	"exports": {
		"./package.json": "./package.json",
		".": {
			"types": "./dist/index.d.ts",
			"bun": "./dist/bun/index.js",
			"import": "./dist/index.mjs",
			"require": "./dist/cjs/index.js"
		}
        }
}
```

This should have fixed the problem with import and require separately.

Closing as not going to not in the roadmap to remove default export, feel free to add further discussion if necessary.
