### ISSUE TITLE
ReferenceError: Can't find variable: k7

### ISSUE THREAD

**Issue by yatagasaru** [elysiajs/elysia#447]
### What steps can reproduce the bug?

```
bun create elysia app
bun run dev
```

### What is the expected behavior?

Elysisa server running

### What do you see instead?

```
ReferenceError: Can't find variable: k7
      at /app/node_modules/elysia/dist/bun/index.js:365:4540
```

**Comment by SaltyAom** [comment]
Fixed with https://github.com/elysiajs/elysia/commit/bca50aecf761e482bbd2e43daa6fce5b6c427bc8, published on 0.8.14 with a test case.

Retrying a command again should have resolved an error, otherwise update Elysia to `>= 0.8.13` or `<= 0.8.10` should have fixed an error as well.

We were using `Bun.build` on Bun 1.0.22, then updated to 1.0.25 causing a regression to `export * from '@sinclair/typebox/system' for some reason, going to report on Bun issue.

Fixed by using named export instead.

Let me know if the problem still persists
