### ISSUE TITLE
Elysia throws error if `Headers#toJSON` doesn't exist

### ISSUE THREAD

**Issue by bogeychan** [elysiajs/elysia#48]
### Output
![image](https://github.com/elysiajs/elysia/assets/109291149/35f60fdd-2afe-4ade-861c-c7e4e4952db7)

### Code
Is this check / fallback still required?
https://github.com/elysiajs/elysia/blob/08a4375b91d9d359fe7a0264b29d7512a729ea8f/src/compose.ts#L211-L219

**Comment by SaltyAom** [comment]
Yes, thanks for inspecting the code, the error comes from that line and is now fixed in Elysia 0.5.10 in this commit https://github.com/elysiajs/elysia/commit/9db731df33d8fc68948ffb3d790258680b53c6c3

Furthermore, when you were using CommonJS you might get an error from Memorist accidentally shipping ES Module instead CommonJS problem which is also solved in the same release.
