### ISSUE TITLE
Elysia is defeated by old js frameworks.

### ISSUE THREAD

**Issue by jim-king-2000** [elysiajs/elysia#64]
1. See here: <https://web-frameworks-benchmark.netlify.app/result?l=javascript>
1. The throughput of `elysia` is after `fastify`, `koa` and `restify`.
1. Any way to improve?

**Comment by SaltyAom** [comment]
I think because of this:
> Hmm, I dig it a bit, my guess is that since Node is using pm2-runtime, it's spawning multi-process to run multiple servers in parallel.
> Fast, Deno-based one is also slower as well.
> HyperExpress couldn't outperform Fiber multithreaded without this as well.
> So kinda make sense.

https://twitter.com/saltyAom/status/1681697389189668864?s=20

You can see on this PR that Node is using pm2-runtime.

So basically because Node framework uses multi-process, (using multiple threads to spawn servers simultaneously) therefore, Elysia is slower because, on that benchmark, any Bun-based framework uses only single-thread, therefore not quite fair.

**Comment by jim-king-2000** [comment]
Thank you very much for the analysis and quick response. How to modify the benchmark to create a fair comparison?

**Comment by waghanza** [comment]
Hi @jim-king-2000  @SaltyAom ,

The purpose of the benchmark you notice is to reflect common usage in real workloads.

It's a common practice to use `pm2` on top of `node` in order to spawn multiple processes.

Is there not such a thing is bun and deno communities?

**Comment by jim-king-2000** [comment]
> So basically because Node framework uses multi-process, (using multiple threads to spawn servers simultaneously) therefore, Elysia is slower because, on that benchmark, any Bun-based framework uses only single-thread, therefore not quite fair.


Do you mean that we should also run `bun` relevant tests with `pm2-runtime`?

**Comment by jim-king-2000** [comment]
Apply the change to both `deno` and `bun` frameworks. And I'm looking forward to the new benchmark result.

**Comment by jim-king-2000** [comment]
> Not sure about practices for running bun on production @SaltyAom


Also use `pm2`.

**Comment by waghanza** [comment]
Could you provide me both command ?

**Comment by SaltyAom** [comment]
It's fine to use PM2 to run Bun server.

For Bun, I would recommend using this command.
```bash
pm2-runtime start "NODE_ENV=production bun src/index.ts" -i max
```

As for Deno, I think @waghanza command would also be working fine.

**Comment by SaltyAom** [comment]
Also, this is from Jarred (Creator of Bun), may I ask this question as well?

He suggests that the slower response might be due to the usage of HTTP 1.0 or Keep Alive being disabled.

<img width="597" alt="image" src="https://github.com/elysiajs/elysia/assets/35027979/5e7e38b2-19f5-4aae-963a-f1bc70a3cfc5">

**Comment by waghanza** [comment]
Could you open PR for `pm2` @jim-king-2000

We use **keep alive** @SaltyAom 
https://github.com/the-benchmarker/web-frameworks/blob/bd09015eb57e9b0b2aab5dbee2ed577671275caf/.tasks/collect.rake#L70

**Comment by jim-king-2000** [comment]
> Could you open PR for pm2 @jim-king-2000 ?


Sure.

**Comment by jim-king-2000** [comment]
I turned the benchmark of `bun` and `deno` to multi-processing. Let's see the new result.

**Comment by jim-king-2000** [comment]
new result: <https://web-frameworks-benchmark.netlify.app/result?l=javascript>
