### ISSUE TITLE
There is not custom http exception in elysia

### ISSUE THREAD

**Issue by DeepanshuKacher** [elysiajs/elysia#910]
### What is the problem this feature would solve?

Previously I was using nest.js in node.js enviornment now testing bun.js and elysia for my new project, elysia is good but when it comes to error handeling elysia don't give any custom http exception 

for example here is hono code :-
```

import { HTTPException } from 'hono/http-exception'

app.post('/auth', async (c, next) => {
  // authentication
  if (authorized === false) {
    throw new HTTPException(401, { message: 'Custom error message' })
  }
  await next()
})
```

it's similar to nest.js where developer have the ablitiy to throw error message **with status code** elysia lack that functionality

I know elysia have 3 http exceptions like Internal Server Exception, Conflict and NotFound, but those are not enough, having a custom http exception which give ability to developer to throw error with status code is required.

### What is the feature you are proposing to solve the problem?

Developer will have to ability to throw http exception with proper status code. 

Required features for headless cms

A proper error status code tells a lot for some front-end network request libraries like axios, also helpful for debugging process

**Comment by Scooter1337** [comment]
```typescript
throw error(401, { message: 'Custom error message' });
```

But custom error messages are better:
https://elysiajs.com/essential/life-cycle.html#custom-error

**Comment by SaltyAom** [comment]
As @Scooter1337 responded, we have an `error` that accepts both numeric HTTP status and full HTTP name compatibility as mentioned in [returning custom HTTP status](https://elysiajs.com/essential/handler.html#status).

Closing as not planned and likely not going to be implemented (since it's duplicated with `error` function)

Despite the issue may be closed, feels free to continue the discussion.
